import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import WalletContextProvider from "@/components/walletProvider";
import { Toaster } from 'sonner'
import { Buffer } from 'buffer';
import Image from "next/image";
global.Buffer = Buffer;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lethe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletContextProvider>
          <ViewTransitions>
            <div className="fixed inset-0 -z-10 bg-background">
              <div className="fixed inset-0 bg-[radial-gradient(circle_at_center,_transparent_0%,_hsl(var(--background))_100%)] pointer-events-none">
                <div className="absolute inset-0" style={{
                  backgroundImage: `radial-gradient(circle at 25% 25%, hsl(var(--primary) / 0.1) 0%, transparent 50%),
                                   radial-gradient(circle at 75% 75%, hsl(var(--glow-secondary) / 0.1) 0%, transparent 50%),
                                   radial-gradient(circle at 50% 10%, hsl(var(--primary) / 0.05) 0%, transparent 50%)`
                }} />
              </div>
            </div>
            <div className="relative z-0 flex flex-col min-h-screen">
              {children}
            </div>
            <Toaster richColors position="bottom-center"/>
          </ViewTransitions>
        </WalletContextProvider>
      </body>
    </html>
  );
}
